version: '3'

services:
  model-training:
    build:
      context: .
      dockerfile: Dockerfile.model
    command: python gridSearchCV.py
    volumes:
      - .:/app
    # Optional: to keep the container running after execution (for debugging)
    # stdin_open: true
    # tty: true

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    depends_on:
      - model-training

