name: Model Training and Evaluations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model training and evaluation
      run: |
        python model.py
        python experiment.py
        python gridSearchCV.py

    - name: Commit and push the model files
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add model_20240801184047.joblib
        git add exp_bestmodel_20240801_191151.joblib
        git add exp_bestmodel_20240801_194023.joblib
        git add 20240801_163255_best_model.joblib
        git add report.md
        git commit -m "Add model and report with timestamp"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
